name: stress-ng-dev
base: core24
adopt-info: version
summary: Stress-ng for Ubuntu Core
description: |
  This snap package includes stress-ng (licensed under GPL-2) along with multiple dependencies under various licenses.
  License files for all bundled projects can be found inside the snap package at `./usr/share`.
  
  The snap is intended for use on Ubuntu Core (https://ubuntu.com/core) only.
  
  For Ubuntu Server/Desktop, install the `stress-ng` Debian package.
  
  For other installation methods, refer to:
  https://github.com/ColinIanKing/stress-ng/blob/master/README.md

  For source code of the snap packaging, refer to:
  https://github.com/canonical/stress-ng-snap
  
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

grade: stable
confinement: devmode

parts:
  version:
    source: .
    plugin: nil
    build-packages:
      - git
      - stress-ng
    override-build: |
      craftctl default
      craftctl set version=$(stress-ng --version | cut -d ' ' -f 3)+$(git rev-parse --short HEAD)

  stress-ng:
    plugin: nil
    stage-packages:
      - stress-ng

apps:
  stress-ng:
    command: usr/bin/stress-ng
